### ISSUE TITLE
Script arnft.worker.js is missing when installing just with npm

### ISSUE THREAD

**Issue by Zaniyar** [j-era/react-three-arnft#3]
By setting up a new project for react and installing the package the arnft.worker.js is missing. 

`GET http://127.0.0.1:5174/js/arnft.worker.js 404 (Not Found)
`
by copying the file into public/js/ you will get this error:

```
Uncaught DOMException: Failed to execute 'importScripts' on 'WorkerGlobalScope': The script at 'http://127.0.0.1:5174/js/ARToolkitNFT_simd.js' failed to load.
    at http://127.0.0.1:5174/js/arnft.worker.js:32:3
(anonymous) @ arnft.worker.js:32
```
The build works. So those files are in the dist of the node modules... but why it can't find them?

By copying them from the node modules dist folder into public/js/ this error happens:

```
001c8da2:0x5d8b Uncaught RuntimeError: null function or function signature mismatch
    at 001c8da2:0x5d8b
    at 001c8da2:0x3c904
    at 001c8da2:0x5fd0b
    at 001c8da2:0x5985b
    at A.detectNFTMarker (eval at AI (ARToolkitNFT_simd.js:2:679129), <anonymous>:8:10)
    at A.value (ARToolkitNFT_simd.js:2:743486)
    at A.value (ARToolkitNFT_simd.js:2:742712)
    at process (arnft.worker.js:115:18)
    at self.onmessage (arnft.worker.js:58:7)
```

Instead of webpack I am using vite.

**Comment by slaymantis** [comment]
I am using Gatsby and React
I managed to get this working.
I copied ARToolkitNFT.js and ARToolkitNFT_simd.js and put it into the js folder with arnft.worker.js
https://github.com/webarkit/jsartoolkitNFT/tree/master/dist

These are my dependencies in the pacakge.json file I am using
 "dependencies": {
    "@mdx-js/react": "^2.3.0",
    "@react-three/drei": "^9.57.3",
    "@react-three/fiber": "^8.12.0",
    "@webarkit/ar-nft": "^0.14.5",
    "@webarkit/jsartoolkit-nft": "^1.4.0",
    "gatsby": "^5.7.0",
    "gatsby-plugin-google-analytics": "^5.7.0",
    "gatsby-plugin-image": "^3.7.0",
    "gatsby-plugin-manifest": "^5.7.0",
    "gatsby-plugin-mdx": "^5.7.0",
    "gatsby-plugin-sass": "^6.7.0",
    "gatsby-plugin-sharp": "^5.7.0",
    "gatsby-plugin-sitemap": "^6.7.0",
    "gatsby-source-filesystem": "^5.7.0",
    "gatsby-transformer-sharp": "^5.7.0",
    "install": "^0.13.0",
    "npm": "^9.6.1",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "react-three-arnft": "^0.3.1",
    "sass": "^1.59.3",
    "three": "^0.150.1"
  }

**Comment by Zaniyar** [comment]
You don't get this error after some time?

```
001c8da2:0x5d8b Uncaught RuntimeError: null function or function signature mismatch
    at 001c8da2:0x5d8b
    at 001c8da2:0x3c904
    at 001c8da2:0x5fd0b
    at 001c8da2:0x5985b
    at A.detectNFTMarker (eval at AI (ARToolkitNFT_simd.js:2:679129), <anonymous>:8:10)
    at A.value (ARToolkitNFT_simd.js:2:743486)
    at A.value (ARToolkitNFT_simd.js:2:742712)
    at process (arnft.worker.js:115:18)
    at self.onmessage (arnft.worker.js:58:7)
$func143 @ 001c8da2:0x5d8b
$func913 @ 001c8da2:0x3c904
$func1124 @ 001c8da2:0x5fd0b
$func1084 @ 001c8da2:0x5985b
detectNFTMarker @ VM15:8
value @ ARToolkitNFT_simd.js:2
value @ ARToolkitNFT_simd.js:2
process @ arnft.worker.js:115
self.onmessage @ arnft.worker.js:58


9xUnchecked runtime.lastError: A listener indicated an asynchronous response by returning true, but the message channel closed before a response was received
```
